/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package problem1;

import java.io.InputStream;


public class Problem1 {

    public static void main(String[] args) {
        Problem1 problem1 = new Problem1();
        problem1.solveProblem1();
        problem1.solveProblem2();
    }

    private void solveProblem1() {
        InputStream problemInput = getClass().getResourceAsStream("/RealInput.txt");
        System.out.println("Problem 1_1 solution: " + solveProblem1(problemInput));
    }

    private void solveProblem2() {
        InputStream problemInput = getClass().getResourceAsStream("/RealInput.txt");
        System.out.println("Problem 1_2 solution: " + solveProblem2(problemInput));
    }

    int solveProblem1(InputStream problemInput) {
        return new Problem1_1().solve(problemInput);
    }

    int solveProblem2(InputStream problemInput) {
        return new Problem1_2().solve(problemInput);
    }
}
