/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc21;

import java.io.InputStream;

public class Problem8 {

    public static void main(String[] args) {
        Problem8 problem8 = new Problem8();
        problem8.solveProblem1();
        problem8.solveProblem2();
    }

    private void solveProblem1() {
        InputStream problemInput = getClass().getResourceAsStream("/RealInput.txt");
        System.out.println(solveProblem1(problemInput));
    }

    private void solveProblem2() {
        InputStream problemInput = getClass().getResourceAsStream("/RealInput.txt");
        System.out.println(solveProblem2(problemInput));
    }

    int solveProblem1(InputStream problemInput) {
        return new Problem8_1().solve(problemInput);
    }

    int solveProblem2(InputStream problemInput) {
        return new Problem8_2().solve(problemInput);
    }
}
