/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc21;

import java.io.InputStream;

public class Problem7 {

    public static void main(String[] args) {
        Problem7 problem7 = new Problem7();
        problem7.solveProblem1();
        problem7.solveProblem2();
    }

    private void solveProblem1() {
        InputStream problemInput = getClass().getResourceAsStream("/RealInput.txt");
        System.out.println(solveProblem1(problemInput));
    }

    private void solveProblem2() {
        InputStream problemInput = getClass().getResourceAsStream("/RealInput.txt");
        System.out.println(solveProblem2(problemInput));
    }

    int solveProblem1(InputStream problemInput) {
        return new Problem7_1().solve(problemInput);
    }

    int solveProblem2(InputStream problemInput) {
        return new Problem7_2().solve(problemInput);
    }
}