/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package problem2;

import java.io.InputStream;

public class Problem2 {

    public static void main(String[] args) {
        Problem2 problem2 = new Problem2();
        problem2.solveProblem1();
        problem2.solveProblem2();
    }

    private void solveProblem1() {
        InputStream problemInput = getClass().getResourceAsStream("/RealInput.txt");
        System.out.println("Problem 2_1 solution: " + solveProblem1(problemInput));
    }

    private void solveProblem2() {
        InputStream problemInput = getClass().getResourceAsStream("/RealInput.txt");
        System.out.println("Problem 2_2 solution: " + solveProblem2(problemInput));
    }

    int solveProblem1(InputStream problemInput) {
        return new Problem2_1().solve(problemInput);
    }

    int solveProblem2(InputStream problemInput) {
        return new Problem2_2().solve(problemInput);
    }
}
